services:
  Mordhau-Wine:
    restart: unless-stopped
    container_name: mordhau-server
    image: m7mdbinghaith/mordhau
    network_mode: "bridge"
    volumes:
      - ./mordhau/server:/mordhau
      - ./mordhau/config:/config
    ports:
      - "7777:7777/udp"
      - "27015:27015/udp"
      - "15000:15000/udp"
      - "2766:2766"
    environment:
      - UID=1000
    cap_add:
      - CAP_NET_ADMIN

volumes:
  mordhau-data:
  mordhau-config:
