version: '3.3'

services:
  Mordhau-Wine:
    restart: unless-stopped
    container_name: mordhau
    image: kamoodovsky/mordhau
    network_mode: "bridge"
    volumes:
      - /home/mohammad/mordhau/server:/mordhau
      - /home/mohammad/mordhau/config:/config
    tty: true
    ports:
      - "7777:7777/udp"
      - "27015:27015/udp"
      - "15000:15000/udp"
    environment:
      - UID=1000
      #- Port=7777
      #- QueryPort=27015
      #- BeaconPort=15000
    cap_add:
      - CAP_NET_ADMIN
